version: '2'
services:
  app1:
    restart: always
    build: ./app1
    ports:
      - "5000:5000"
  #app2:
  #  restart: always
  #  build: ./app2
  #  ports:
  #    - "5000:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    network_mode: "host"
